address_data is missing subnetwork
this is a quick work around for 
```
File "/src/apache-libcloud/libcloud/compute/drivers/gce.py", line 2921, in ex_create_address
  data=address_data)
File "/src/apache-libcloud/libcloud/common/base.py", line 772, in async_request
  response = request(**kwargs)
File "/src/apache-libcloud/libcloud/compute/drivers/gce.py", line 121, in request
  response = super(GCEConnection, self).request(*args, **kwargs)
File "/src/apache-libcloud/libcloud/common/google.py", line 808, in request
  *args, **kwargs)
File "/src/apache-libcloud/libcloud/common/base.py", line 637, in request
  response = responseCls(**kwargs)
File "/src/apache-libcloud/libcloud/common/base.py", line 155, in __init__
  self.object = self.parse_body()
File "/src/apache-libcloud/libcloud/common/google.py", line 288, in parse_body
  raise InvalidRequestError(message, self.status, code)
InvalidRequestError: {u'domain': u'global', u'message': u"Invalid value for field 'resource.subnetwork': ''. No default subnetwork was found for an address with type INTERNAL.", u'reason': u'invalid'}
 ```