Add py3.5-lxml to tox.ini
So I can construct a bytes vs str test case that fails reproducibly under Python 3. Turned out there were already several so no need:

ERROR: test_create_group_location_does_not_exist (libcloud.test.compute.test_abiquo.AbiquoNodeDriverTest)
...(not all 595 errors shown)
ERROR: test_update_target (libcloud.test.backup.test_dimensiondata.DimensionDataTests)
ERROR: test_update_target_DEFAULT (libcloud.test.backup.test_dimensiondata.DimensionDataTests)
ERROR: test_update_target_STR (libcloud.test.backup.test_dimensiondata.DimensionDataTests)
FAIL: test_wait_until_running_running_multiple_nodes_have_same_uuid (libcloud.test.compute.test_deployment.DeploymentTests)
FAIL: test_wait_until_running_running_node_missing_from_list_nodes (libcloud.test.compute.test_deployment.DeploymentTests)
FAIL: test_wait_until_running_timeout (libcloud.test.compute.test_deployment.DeploymentTests)
FAIL: test_ex_set_control_access (libcloud.test.compute.test_vcloud.VCloud_1_5_Tests)
FAILED (failures=4, errors=595, skipped=14)

Others can let me know if it's a worthwhile trade off to add lxml testing against all environments.