Fix publickey._to_md5_fingerprint for Python 3
In Python 3, the original code didn't work, because there is no `encode`
function for binaries:

    (Python3.3)>>> [x.encode("hex") for x in b"abc"]
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "<stdin>", line 1, in <listcomp>
    AttributeError: 'int' object has no attribute 'encode'

String do have an `encode` method, but it is a different function from the
`encode` in Python 2:

    (Python3.3)>>> [x.encode("hex") for x in "abc"]
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "<stdin>", line 1, in <listcomp>
    LookupError: unknown encoding: hex

So I added a "hexadigits" function to our compatibility module (py3) and used
that in _to_md5_fingerprint.